// <auto-generated />
using System;
using DocMigrate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace DocMigrate.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocMigrate.Domain.Entities.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paginasid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("corfundo");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("criadoporusuarioid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icone");

                    b.Property<string>("IconColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("coricone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("pt-BR")
                        .HasColumnName("idioma");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("bloqueadoem");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bloqueadopor");

                    b.Property<string>("PlainText")
                        .HasColumnType("text")
                        .HasColumnName("textoplano");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("busca")
                        .HasComputedColumnSql("to_tsvector('portuguese', coalesce(titulo, '') || ' ' || coalesce(descricao, '') || ' ' || coalesce(textoplano, ''))", true);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<int>("SpaceId")
                        .HasColumnType("integer")
                        .HasColumnName("espacoid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizadoporusuarioid");

                    b.HasKey("Id")
                        .HasName("pk_paginas");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_paginas_desativadoem")
                        .HasFilter("desativadoem IS NULL");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_paginas_busca");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("SpaceId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("paginas", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paginascomentariosid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("autorid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("paginaid");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comentariopaiid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_paginas_comentarios");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("idx_paginas_comentarios_autorid");

                    b.HasIndex("PageId")
                        .HasDatabaseName("idx_paginas_comentarios_paginaid");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("paginas_comentarios", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paginasfavoritasid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("paginaid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_paginas_favoritas");

                    b.HasIndex("PageId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_paginas_favoritas_usuarioid");

                    b.HasIndex("UserId", "PageId")
                        .IsUnique()
                        .HasDatabaseName("uq_paginas_favoritas_usuarioid_paginaid");

                    b.ToTable("paginas_favoritas", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paginastraducoesid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("idioma");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("paginaid");

                    b.Property<string>("PlainText")
                        .HasColumnType("text")
                        .HasColumnName("textoplano");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector")
                        .HasColumnName("busca");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hashorigem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("automatica")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.Property<int?>("TranslatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("traduzidopor");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_paginas_traducoes");

                    b.HasIndex("PageId")
                        .HasDatabaseName("idx_paginas_traducoes_paginaid");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_paginas_traducoes_busca");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("TranslatedByUserId");

                    b.HasIndex("PageId", "Language")
                        .IsUnique()
                        .HasDatabaseName("uq_paginas_traducoes_paginaid_idioma")
                        .HasFilter("desativadoem IS NULL");

                    b.ToTable("paginas_traducoes", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paginasversoesid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricaomudanca");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("criadoporusuarioid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("paginaid");

                    b.Property<string>("PlainText")
                        .HasColumnType("text")
                        .HasColumnName("textoplano");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("versaonumero");

                    b.HasKey("Id")
                        .HasName("pk_paginas_versoes");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PageId")
                        .HasDatabaseName("idx_paginas_versoes_paginaid");

                    b.HasIndex("PageId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_paginas_versoes_paginaid_versaonumero");

                    b.ToTable("paginas_versoes", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paginasvisitasid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("paginaid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<DateTime>("VisitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("visitadoem")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_paginas_visitas");

                    b.HasIndex("PageId");

                    b.HasIndex("UserId", "VisitedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_paginas_visitas_usuarioid_visitadoem");

                    b.ToTable("paginas_visitas", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.Space", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("espacosid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("corfundo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("criadoporusuarioid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icone");

                    b.Property<string>("IconColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("coricone");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("busca")
                        .HasComputedColumnSql("to_tsvector('portuguese', coalesce(titulo, '') || ' ' || coalesce(descricao, ''))", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizadoporusuarioid");

                    b.HasKey("Id")
                        .HasName("pk_espacos");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_espacos_desativadoem")
                        .HasFilter("desativadoem IS NULL");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_espacos_busca");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("espacos", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tagsid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_tags_desativadoem")
                        .HasFilter("desativadoem IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_tags_nome")
                        .HasFilter("desativadoem IS NULL");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("templatesid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("criadoporusuarioid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icone");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("padrao");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizadoporusuarioid");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_templates_desativadoem")
                        .HasFilter("desativadoem IS NULL");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuariosid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keycloakid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("admin")
                        .HasColumnName("perfil");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_usuarios_desativadoem")
                        .HasFilter("desativadoem IS NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_email");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_keycloakid");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@docmigrate.local",
                            KeycloakId = "seed-admin",
                            Name = "Administrador",
                            Role = "admin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("preferenciasid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("desativadoem");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("configuracoes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizadoem")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id")
                        .HasName("pk_preferencias");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_preferencias_desativadoem")
                        .HasFilter("desativadoem IS NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_preferencias_usuarioid")
                        .HasFilter("desativadoem IS NULL");

                    b.ToTable("preferencias", (string)null);
                });

            modelBuilder.Entity("espacos_tags", b =>
                {
                    b.Property<int>("espacoid")
                        .HasColumnType("integer");

                    b.Property<int>("tagid")
                        .HasColumnType("integer");

                    b.HasKey("espacoid", "tagid")
                        .HasName("pk_espacos_tags");

                    b.HasIndex("tagid");

                    b.ToTable("espacos_tags", (string)null);
                });

            modelBuilder.Entity("paginas_tags", b =>
                {
                    b.Property<int>("paginaid")
                        .HasColumnType("integer");

                    b.Property<int>("tagid")
                        .HasColumnType("integer");

                    b.HasKey("paginaid", "tagid")
                        .HasName("pk_paginas_tags");

                    b.HasIndex("tagid");

                    b.ToTable("paginas_tags", (string)null);
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.Page", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_paginas_criadoporusuarioid");

                    b.HasOne("DocMigrate.Domain.Entities.Space", "Space")
                        .WithMany("Pages")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_espacoid");

                    b.HasOne("DocMigrate.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_paginas_atualizadoporusuarioid");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Space");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageComment", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_paginas_comentarios_autorid");

                    b.HasOne("DocMigrate.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_comentarios_paginaid");

                    b.HasOne("DocMigrate.Domain.Entities.PageComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_paginas_comentarios_comentariopaiid");

                    b.Navigation("Author");

                    b.Navigation("Page");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageFavorite", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_favoritas_paginaid");

                    b.HasOne("DocMigrate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_favoritas_usuarioid");

                    b.Navigation("Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageTranslation", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_traducoes_paginaid");

                    b.HasOne("DocMigrate.Domain.Entities.User", "TranslatedByUser")
                        .WithMany()
                        .HasForeignKey("TranslatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_paginas_traducoes_traduzidopor");

                    b.Navigation("Page");

                    b.Navigation("TranslatedByUser");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageVersion", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_paginas_versoes_criadoporusuarioid");

                    b.HasOne("DocMigrate.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_versoes_paginaid");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageVisit", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_visitas_paginaid");

                    b.HasOne("DocMigrate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_visitas_usuarioid");

                    b.Navigation("Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.Space", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_espacos_criadoporusuarioid");

                    b.HasOne("DocMigrate.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_espacos_atualizadoporusuarioid");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.Template", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_templates_criadoporusuarioid");

                    b.HasOne("DocMigrate.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_templates_atualizadoporusuarioid");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("DocMigrate.Domain.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preferencias_usuarioid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("espacos_tags", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.Space", null)
                        .WithMany()
                        .HasForeignKey("espacoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_espacos_tags_espacoid");

                    b.HasOne("DocMigrate.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tagid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_espacos_tags_tagid");
                });

            modelBuilder.Entity("paginas_tags", b =>
                {
                    b.HasOne("DocMigrate.Domain.Entities.Page", null)
                        .WithMany()
                        .HasForeignKey("paginaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_tags_paginaid");

                    b.HasOne("DocMigrate.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tagid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paginas_tags_tagid");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.PageComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.Space", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DocMigrate.Domain.Entities.User", b =>
                {
                    b.Navigation("Preference");
                });
#pragma warning restore 612, 618
        }
    }
}
